/* APEX – Mittagsgerichte (sättigende Hauptmahlzeiten, ~450–650 kcal, klare Proteinquelle + Gemüse + Beilage)
   Format: { n:Name, i:[[zutatId, gramm], ...], t:[tags] }  – kcal berechnet die App.
   Bei Reis/Nudeln/Couscous/Bulgur/Quinoa/Polenta = Rohgewicht. Bei Öl/Sauce/Kokosmilch/Brühe = ml. */

window.MEALS_LUNCH = [
  { n: "Hähnchen-Reis-Bowl mit Brokkoli", i: [["chicken", 150], ["rice", 70], ["broccoli", 150], ["oliveoil", 8], ["soysauce", 10]], t: ["herzhaft", "protein", "warm"] },
  { n: "Teriyaki-Hähnchen mit Reis & Edamame", i: [["chicken", 150], ["rice", 70], ["edamame", 80], ["soysauce", 15], ["sesame", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Putenpfanne mit Paprika & Naturreis", i: [["turkey", 150], ["ricebrown", 70], ["pepper", 120], ["onion", 40], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Rindersteak mit Kartoffeln & grünen Bohnen", i: [["beefsteak", 140], ["potato", 250], ["greenbeans", 150], ["oliveoil", 8], ["herbs", 3]], t: ["herzhaft", "protein", "warm"] },
  { n: "Lachsfilet mit Quinoa & Spinat", i: [["salmon", 130], ["quinoa", 60], ["spinach", 120], ["oliveoil", 6], ["lemon", 15]], t: ["herzhaft", "protein", "warm"] },
  { n: "Kabeljau mit Kartoffeln & Erbsen", i: [["cod", 160], ["potato", 250], ["peas", 120], ["butter", 8], ["herbs", 3]], t: ["herzhaft", "protein", "warm"] },
  { n: "Garnelen-Nudeln mit Zucchini & Knoblauch", i: [["shrimp", 150], ["pasta", 75], ["zucchini", 120], ["garlic", 8], ["oliveoil", 10]], t: ["herzhaft", "protein", "warm"] },
  { n: "Tofu-Curry mit Kokosmilch & Reis", i: [["tofu", 150], ["rice", 70], ["pepper", 100], ["coconutmilk", 60], ["currypaste", 20], ["broccoli", 100]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Rote-Linsen-Curry mit Reis", i: [["lentilsred", 70], ["rice", 60], ["coconutmilk", 60], ["curry", 6], ["carrot", 80], ["spinach", 80]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Kichererbsen-Curry mit Naturreis", i: [["chickpeas", 150], ["ricebrown", 65], ["passata", 100], ["coconutmilk", 50], ["curry", 6], ["onion", 40]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Spaghetti Bolognese mit Rinderhack", i: [["beefmince", 130], ["pasta", 75], ["passata", 120], ["onion", 40], ["garlic", 6], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Linsen-Bolognese mit Vollkornnudeln", i: [["lentils", 150], ["pasta", 75], ["passata", 120], ["onion", 40], ["tomatopaste", 15], ["oliveoil", 8]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Soja-Bolognese mit Nudeln", i: [["soyveg", 40], ["pasta", 75], ["passata", 130], ["onion", 40], ["garlic", 6], ["oliveoil", 8]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Chili con Carne mit Kidneybohnen", i: [["beefmince", 120], ["beans", 120], ["corn", 80], ["passata", 120], ["onion", 40], ["chili", 5]], t: ["herzhaft", "protein", "warm"] },
  { n: "Chili sin Carne mit Bohnen & Mais", i: [["beans", 150], ["chickpeas", 130], ["corn", 90], ["passata", 130], ["onion", 40], ["rice", 45]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Hähnchen-Fajita-Wrap mit Paprika", i: [["chicken", 130], ["wrap", 64], ["pepper", 100], ["onion", 40], ["oliveoil", 6], ["cheese", 20]], t: ["herzhaft", "protein"] },
  { n: "Puten-Wrap mit Frischkäse & Rucola", i: [["turkey", 120], ["wrap", 64], ["cheesecreamlt", 30], ["rocket", 30], ["tomato", 50]], t: ["herzhaft", "protein"] },
  { n: "Falafel-Wrap mit Hummus & Salat", i: [["chickpeas", 130], ["wrap", 64], ["hummus", 30], ["lettuce", 40], ["tomato", 50], ["cucumber", 40]], t: ["herzhaft", "vegan"] },
  { n: "Thunfisch-Wrap mit Mais & Salat", i: [["tuna", 100], ["wrap", 64], ["corn", 60], ["lettuce", 40], ["cheesecreamlt", 25]], t: ["herzhaft", "protein"] },
  { n: "Hähnchensalat mit Ei & Croûtons", i: [["chicken", 130], ["lettuce", 80], ["egg", 60], ["tomatocherry", 80], ["wgbread", 45], ["oliveoil", 8]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Griechischer Salat mit Feta & Pita", i: [["feta", 60], ["cucumber", 100], ["tomato", 100], ["onionred", 40], ["olives", 30], ["pita", 70], ["oliveoil", 8]], t: ["herzhaft", "vegetarisch"] },
  { n: "Caprese-Salat mit Mozzarella & Brot", i: [["cheesemozz", 100], ["tomato", 150], ["rocket", 30], ["wgbread", 90], ["pesto", 15], ["oliveoil", 6]], t: ["herzhaft", "vegetarisch", "kalt"] },
  { n: "Quinoa-Bowl mit Kichererbsen & Avocado", i: [["quinoa", 60], ["chickpeas", 120], ["avocado", 60], ["tomatocherry", 80], ["spinach", 60], ["lemon", 10]], t: ["herzhaft", "vegan"] },
  { n: "Buddha-Bowl mit Tofu & Süßkartoffel", i: [["tofu", 130], ["sweetpotato", 200], ["chickpeas", 80], ["spinach", 60], ["sesame", 6], ["oliveoil", 8]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Poke-Bowl mit Lachs & Edamame", i: [["salmon", 110], ["rice", 65], ["edamame", 70], ["cucumber", 60], ["avocado", 40], ["soysauce", 12]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Poke-Bowl mit Thunfisch & Mango", i: [["tuna", 120], ["rice", 70], ["mango", 80], ["cucumber", 60], ["edamame", 60], ["soysauce", 12]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Hähnchen-Nudelpfanne asiatisch", i: [["chicken", 150], ["pastawhite", 70], ["pepper", 80], ["carrot", 60], ["soysauce", 15], ["sesame", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Rindfleisch-Wok mit Brokkoli & Reis", i: [["beefsteak", 130], ["rice", 70], ["broccoli", 120], ["carrot", 60], ["soysauce", 15], ["ginger", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Süßkartoffel-Curry mit Kichererbsen", i: [["sweetpotato", 200], ["chickpeas", 120], ["coconutmilk", 60], ["curry", 6], ["spinach", 60], ["onion", 40]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Kürbis-Kokos-Suppe mit Kichererbsen", i: [["pumpkin", 250], ["chickpeas", 180], ["coconutmilk", 80], ["broth", 150], ["ginger", 8], ["pumpkinseed", 15], ["roll", 70]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Linseneintopf mit Karotten & Lauch", i: [["lentils", 180], ["carrot", 100], ["leek", 60], ["potato", 120], ["broth", 200], ["oliveoil", 6]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Erbseneintopf mit Kochschinken", i: [["peas", 200], ["ham", 60], ["potato", 150], ["carrot", 80], ["broth", 200], ["onion", 40]], t: ["herzhaft", "protein", "warm"] },
  { n: "Minestrone mit weißen Bohnen", i: [["whitebeans", 130], ["pasta", 50], ["carrot", 60], ["celery", 40], ["passata", 100], ["broth", 200]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Hähnchen-Gemüsesuppe mit Nudeln", i: [["chicken", 120], ["pastawhite", 50], ["carrot", 80], ["leek", 50], ["broth", 250], ["peas", 60]], t: ["herzhaft", "protein", "warm"] },
  { n: "Gulaschsuppe mit Rindfleisch", i: [["beefsteak", 130], ["potato", 180], ["pepper", 80], ["passata", 100], ["onion", 50], ["broth", 200]], t: ["herzhaft", "protein", "warm"] },
  { n: "Ofenkartoffel mit Quark & Leinsamen", i: [["potato", 300], ["quark", 150], ["herbs", 5], ["flaxseed", 10], ["oliveoil", 5]], t: ["herzhaft", "protein", "warm"] },
  { n: "Ofenkartoffel mit Thunfisch & Mais", i: [["potato", 300], ["tuna", 100], ["corn", 60], ["cheesecreamlt", 30], ["herbs", 4]], t: ["herzhaft", "protein", "warm"] },
  { n: "Kartoffel-Gemüse-Auflauf mit Käse", i: [["potato", 250], ["broccoli", 100], ["cheese", 40], ["milk", 60], ["egg", 60], ["herbs", 4]], t: ["herzhaft", "vegetarisch", "warm"] },
  { n: "Nudelauflauf mit Hähnchen & Brokkoli", i: [["chicken", 110], ["pasta", 60], ["broccoli", 100], ["cheese", 30], ["milk", 60], ["parmesan", 10]], t: ["herzhaft", "protein", "warm"] },
  { n: "Lasagne mit Rinderhack & Spinat", i: [["beefmince", 120], ["pasta", 60], ["spinach", 80], ["passata", 100], ["cheese", 40], ["milk", 50]], t: ["herzhaft", "protein", "warm"] },
  { n: "Gemüse-Lasagne mit Zucchini", i: [["zucchini", 120], ["pasta", 60], ["passata", 120], ["cheesemozz", 60], ["parmesan", 15], ["oliveoil", 6]], t: ["herzhaft", "vegetarisch", "warm"] },
  { n: "Gnocchi-Pfanne mit Tomaten & Mozzarella", i: [["gnocchi", 250], ["tomatocherry", 120], ["cheesemozz", 80], ["rocket", 30], ["oliveoil", 8], ["garlic", 5]], t: ["herzhaft", "vegetarisch", "warm"] },
  { n: "Gnocchi mit Pesto & Hähnchen", i: [["gnocchi", 200], ["chicken", 120], ["pesto", 15], ["tomatocherry", 80], ["parmesan", 10]], t: ["herzhaft", "protein", "warm"] },
  { n: "Polenta mit Ratatouille", i: [["polenta", 70], ["zucchini", 100], ["eggplant", 100], ["pepper", 80], ["passata", 100], ["oliveoil", 8]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Couscous-Salat mit Feta & Minze", i: [["couscous", 70], ["feta", 60], ["cucumber", 80], ["tomatocherry", 80], ["onionred", 30], ["oliveoil", 8], ["lemon", 10]], t: ["herzhaft", "vegetarisch", "kalt"] },
  { n: "Bulgur-Salat mit Kichererbsen", i: [["bulgur", 70], ["chickpeas", 120], ["tomato", 80], ["cucumber", 60], ["herbs", 6], ["oliveoil", 8], ["lemon", 10]], t: ["herzhaft", "vegan", "kalt"] },
  { n: "Tabouleh mit Kichererbsen & Petersilie", i: [["bulgur", 65], ["chickpeas", 100], ["tomato", 100], ["herbs", 10], ["onionred", 30], ["oliveoil", 8], ["lemon", 12]], t: ["herzhaft", "vegan", "kalt"] },
  { n: "Halloumi-Bowl mit Couscous & Gemüse", i: [["halloumi", 100], ["couscous", 65], ["zucchini", 100], ["pepper", 80], ["oliveoil", 8], ["lemon", 10]], t: ["herzhaft", "vegetarisch", "warm"] },
  { n: "Schweinefilet mit Kartoffeln & Rahmchampignons", i: [["porkfillet", 140], ["potato", 220], ["mushroom", 120], ["creamsour", 40], ["onion", 40], ["herbs", 4]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchenschenkel mit Ofengemüse", i: [["chickenthigh", 150], ["potato", 200], ["carrot", 100], ["zucchini", 80], ["oliveoil", 10], ["herbs", 4]], t: ["herzhaft", "protein", "warm"] },
  { n: "Forelle mit Petersilienkartoffeln", i: [["trout", 150], ["potato", 250], ["butter", 8], ["herbs", 6], ["lemon", 15]], t: ["herzhaft", "protein", "warm"] },
  { n: "Lachs-Teriyaki-Bowl mit Reis", i: [["salmon", 130], ["rice", 70], ["broccoli", 100], ["carrot", 60], ["soysauce", 15], ["honey", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Garnelen-Reispfanne mit Ei", i: [["shrimp", 130], ["rice", 70], ["egg", 60], ["peas", 60], ["carrot", 60], ["soysauce", 12]], t: ["herzhaft", "protein", "warm"] },
  { n: "Gebratener Reis mit Ei & Gemüse", i: [["rice", 75], ["egg", 120], ["peas", 60], ["carrot", 60], ["soysauce", 15], ["sesame", 5]], t: ["herzhaft", "vegetarisch", "warm"] },
  { n: "Tofu-Gemüse-Wok mit Reis", i: [["tofusmoked", 130], ["rice", 70], ["broccoli", 100], ["pepper", 80], ["soysauce", 15], ["ginger", 8]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Tempeh-Bowl mit Erdnusssauce", i: [["tempeh", 120], ["rice", 65], ["broccoli", 100], ["carrot", 60], ["peanut", 15], ["soysauce", 12]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Räuchertofu-Pfanne mit Bulgur", i: [["tofusmoked", 130], ["bulgur", 65], ["zucchini", 100], ["pepper", 80], ["oliveoil", 8], ["herbs", 4]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Kichererbsen-Spinat-Curry", i: [["chickpeas", 150], ["spinach", 100], ["coconutmilk", 60], ["curry", 6], ["onion", 40], ["rice", 60]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Rotes Thai-Curry mit Hähnchen", i: [["chicken", 140], ["rice", 70], ["pepper", 80], ["coconutmilk", 60], ["currypaste", 20], ["greenbeans", 80]], t: ["herzhaft", "protein", "warm"] },
  { n: "Grünes Curry mit Garnelen", i: [["shrimp", 140], ["rice", 70], ["zucchini", 100], ["coconutmilk", 60], ["currypaste", 20], ["broccoli", 80]], t: ["herzhaft", "protein", "warm"] },
  { n: "Süßkartoffel-Linsen-Suppe", i: [["sweetpotato", 200], ["lentilsred", 50], ["coconutmilk", 40], ["broth", 200], ["curry", 5], ["carrot", 80]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Tomaten-Linsen-Suppe mit Feta", i: [["lentilsred", 60], ["passata", 150], ["broth", 200], ["feta", 40], ["onion", 40], ["oliveoil", 6]], t: ["herzhaft", "vegetarisch", "warm"] },
  { n: "Brokkoli-Cremesuppe mit Hähnchen", i: [["broccoli", 200], ["chicken", 100], ["potato", 100], ["milk", 80], ["broth", 200], ["parmesan", 15]], t: ["herzhaft", "protein", "warm"] },
  { n: "Kartoffel-Lauch-Suppe mit Schinken", i: [["potato", 300], ["leek", 80], ["ham", 80], ["milk", 100], ["broth", 150], ["roll", 70]], t: ["herzhaft", "protein", "warm"] },
  { n: "Bohnen-Gemüse-Eintopf", i: [["whitebeans", 200], ["carrot", 80], ["greenbeans", 80], ["potato", 180], ["passata", 100], ["oliveoil", 8]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Grünkohl-Eintopf mit Kartoffeln", i: [["kale", 150], ["potato", 200], ["whitebeans", 100], ["onion", 40], ["broth", 200], ["oliveoil", 8]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Hähnchengeschnetzeltes mit Reis", i: [["chicken", 150], ["rice", 70], ["mushroom", 100], ["pepper", 60], ["creamsour", 40], ["herbs", 4]], t: ["herzhaft", "protein", "warm"] },
  { n: "Zucchini-Nudeln mit Hähnchen & Pesto", i: [["chicken", 140], ["zucchini", 150], ["pasta", 60], ["pesto", 20], ["tomatocherry", 80], ["parmesan", 15]], t: ["herzhaft", "protein", "warm"] },
  { n: "Nudeln mit Lachs & Spinat in Sahnesauce", i: [["salmon", 120], ["pasta", 70], ["spinach", 80], ["cheesecreamlt", 40], ["garlic", 5], ["lemon", 10]], t: ["herzhaft", "protein", "warm"] },
  { n: "Nudeln Arrabiata mit Thunfisch", i: [["tuna", 100], ["pasta", 75], ["passata", 130], ["garlic", 6], ["chili", 4], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Spaghetti Aglio e Olio mit Garnelen", i: [["shrimp", 130], ["pasta", 75], ["garlic", 8], ["oliveoil", 12], ["chili", 4], ["herbs", 5]], t: ["herzhaft", "protein", "warm"] },
  { n: "Nudelsalat mit Ei & Gemüse", i: [["pasta", 70], ["egg", 120], ["pepper", 80], ["tomatocherry", 80], ["cheesecreamlt", 30], ["herbs", 4]], t: ["herzhaft", "vegetarisch", "kalt"] },
  { n: "Nudelsalat mit Putenbrust & Rucola", i: [["turkey", 100], ["pasta", 70], ["rocket", 30], ["tomatocherry", 80], ["parmesan", 15], ["oliveoil", 10]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Reissalat mit Thunfisch & Mais", i: [["tuna", 100], ["rice", 70], ["corn", 70], ["pepper", 70], ["onionred", 30], ["oliveoil", 8]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Linsensalat mit Feta & Tomaten", i: [["lentils", 180], ["feta", 50], ["tomato", 80], ["cucumber", 60], ["onionred", 30], ["oliveoil", 8], ["vinegar", 8]], t: ["herzhaft", "vegetarisch", "kalt"] },
  { n: "Bohnensalat mit Ei & Zwiebel", i: [["whitebeans", 150], ["egg", 120], ["onionred", 30], ["tomato", 80], ["oliveoil", 8], ["vinegar", 8]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Kichererbsensalat mit Avocado", i: [["chickpeas", 200], ["avocado", 80], ["tomatocherry", 80], ["cucumber", 60], ["pumpkinseed", 15], ["oliveoil", 8]], t: ["herzhaft", "vegan", "kalt"] },
  { n: "Rote-Bete-Salat mit Ziegenkäse-Alternative Feta", i: [["beetroot", 150], ["feta", 60], ["rocket", 40], ["walnut", 20], ["oliveoil", 8], ["vinegar", 8]], t: ["herzhaft", "vegetarisch", "kalt"] },
  { n: "Caesar-Salat mit Hähnchen", i: [["chicken", 140], ["lettuce", 100], ["parmesan", 20], ["wgbread", 45], ["yogurtgreek", 40], ["oliveoil", 6]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Feldsalat mit Putenstreifen & Ei", i: [["turkey", 120], ["cornsalad", 60], ["egg", 60], ["tomatocherry", 80], ["walnut", 15], ["oliveoil", 8]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Spinatsalat mit Lachs & Avocado", i: [["salmon", 120], ["spinach", 80], ["avocado", 50], ["tomatocherry", 80], ["oliveoil", 8], ["lemon", 12]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Quinoa-Salat mit Granatapfel & Feta", i: [["quinoa", 65], ["feta", 50], ["pomegranate", 50], ["cucumber", 60], ["rocket", 30], ["oliveoil", 8]], t: ["herzhaft", "vegetarisch", "kalt"] },
  { n: "Tortilla-Bowl mit Hähnchen & Bohnen", i: [["chicken", 130], ["beans", 100], ["corn", 60], ["tortilla", 60], ["lettuce", 40], ["cheese", 25]], t: ["herzhaft", "protein"] },
  { n: "Burrito-Bowl mit Rinderhack & Reis", i: [["beefmince", 110], ["rice", 55], ["beans", 100], ["corn", 60], ["avocado", 35], ["tomato", 60]], t: ["herzhaft", "protein", "warm"] },
  { n: "Veggie-Burrito mit Bohnen & Avocado", i: [["beans", 130], ["tortilla", 60], ["rice", 55], ["avocado", 50], ["corn", 60], ["tomato", 60]], t: ["herzhaft", "vegan"] },
  { n: "Quesadilla mit Hähnchen & Käse", i: [["chicken", 120], ["tortilla", 60], ["cheese", 40], ["pepper", 60], ["onion", 30]], t: ["herzhaft", "protein", "warm"] },
  { n: "Enchilada-Auflauf mit Puten & Bohnen", i: [["turkey", 120], ["tortilla", 60], ["beans", 100], ["passata", 100], ["cheese", 35], ["corn", 50]], t: ["herzhaft", "protein", "warm"] },
  { n: "Shakshuka mit Ei & Feta", i: [["egg", 120], ["passata", 150], ["pepper", 100], ["onion", 40], ["feta", 40], ["wgbread", 45]], t: ["herzhaft", "vegetarisch", "warm"] },
  { n: "Frittata mit Gemüse & Kartoffeln", i: [["egg", 150], ["potato", 150], ["zucchini", 80], ["pepper", 60], ["parmesan", 15], ["oliveoil", 6]], t: ["herzhaft", "vegetarisch", "warm"] },
  { n: "Omelett mit Champignons & Käse", i: [["egg", 150], ["mushroom", 100], ["cheese", 30], ["spinach", 60], ["wgbread", 45], ["butter", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Bratkartoffeln mit Spiegelei & Speck-Alternative Schinken", i: [["potato", 250], ["egg", 120], ["ham", 40], ["onion", 40], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Süßkartoffel-Pommes mit Hähnchen & Dip", i: [["sweetpotato", 220], ["chicken", 130], ["yogurtgreek", 50], ["herbs", 4], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Kürbis-Risotto mit Parmesan", i: [["rice", 75], ["pumpkin", 150], ["parmesan", 25], ["onion", 40], ["broth", 150], ["oliveoil", 8]], t: ["herzhaft", "vegetarisch", "warm"] },
  { n: "Pilz-Risotto mit Hähnchen", i: [["rice", 70], ["chicken", 120], ["mushroom", 120], ["parmesan", 20], ["broth", 150], ["onion", 30]], t: ["herzhaft", "protein", "warm"] },
  { n: "Spargelpfanne mit Lachs & Kartoffeln", i: [["salmon", 120], ["asparagus", 150], ["potato", 200], ["butter", 8], ["lemon", 12], ["herbs", 4]], t: ["herzhaft", "protein", "warm"] },
  { n: "Blumenkohl-Curry mit Kichererbsen", i: [["cauliflower", 200], ["chickpeas", 120], ["coconutmilk", 60], ["curry", 6], ["onion", 40], ["rice", 55]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Auberginen-Curry mit Reis", i: [["eggplant", 180], ["chickpeas", 100], ["passata", 100], ["coconutmilk", 50], ["curry", 6], ["rice", 60]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Edamame-Nudeln mit Erdnusssauce", i: [["edamame", 120], ["pastawhite", 70], ["carrot", 60], ["pepper", 70], ["peanut", 15], ["soysauce", 12]], t: ["herzhaft", "vegan", "warm"] },
  { n: "Low-Carb-Hähnchenpfanne mit Blumenkohlreis", i: [["chicken", 160], ["cauliflower", 200], ["pepper", 80], ["broccoli", 80], ["oliveoil", 8], ["soysauce", 10]], t: ["herzhaft", "protein", "lowcarb", "warm"] },
  { n: "Low-Carb-Lachs mit Spargel & Rucola", i: [["salmon", 150], ["asparagus", 150], ["rocket", 40], ["cheesecreamlt", 30], ["oliveoil", 8], ["lemon", 12]], t: ["herzhaft", "protein", "lowcarb", "warm"] }
];
