/* APEX – Brotzeit für vormittags (kleine, sättigende Mahlzeiten, ~150–320 kcal)
   Format: { n:Name, i:[[zutatId, gramm], ...], t:[tags] }  – kcal berechnet die App. */

window.MEALS_SNACK = [
  { n: "Vollkornbrot mit Putenbrust & Gurke", i: [["wgbread", 90], ["turkeyham", 40], ["cucumber", 40], ["mustard", 5]], t: ["herzhaft", "protein", "schnell"] },
  { n: "Roggenbrot mit Kochschinken & Tomate", i: [["ryebread", 80], ["ham", 40], ["tomato", 50]], t: ["herzhaft", "protein"] },
  { n: "Vollkornbrot mit Frischkäse & Radieschen", i: [["wgbread", 90], ["cheesecreamlt", 30], ["radish", 40]], t: ["herzhaft", "vegetarisch"] },
  { n: "Vollkornbrot mit Ei & Schnittlauch", i: [["wgbread", 90], ["egg", 60], ["herbs", 3]], t: ["herzhaft", "protein"] },
  { n: "Vollkornbrot mit Avocado & Ei", i: [["wgbread", 45], ["avocado", 40], ["egg", 60]], t: ["herzhaft", "protein"] },
  { n: "Vollkornbrot mit Käse & Gurke", i: [["wgbread", 90], ["cheese", 30], ["cucumber", 40]], t: ["herzhaft", "vegetarisch"] },
  { n: "Vollkornbrot mit Thunfisch-Creme", i: [["wgbread", 90], ["tuna", 50], ["cheesecreamlt", 20]], t: ["herzhaft", "protein"] },
  { n: "Vollkornbrötchen mit Frischkäse & Räucherlachs", i: [["roll", 70], ["cheesecreamlt", 30], ["salmonsmoked", 30]], t: ["herzhaft", "protein"] },
  { n: "2 gekochte Eier & Vollkornbrot", i: [["egg", 120], ["wgbread", 45]], t: ["herzhaft", "protein", "schnell"] },
  { n: "Vollkornbrot mit Hummus & Paprika", i: [["wgbread", 90], ["hummus", 30], ["pepper", 60]], t: ["herzhaft", "vegan"] },
  { n: "Knäckebrot mit Hüttenkäse & Tomate", i: [["crispbread", 20], ["cottage", 80], ["tomato", 50]], t: ["herzhaft", "protein", "schnell"] },
  { n: "Knäckebrot mit Avocado & Tomate", i: [["crispbread", 20], ["avocado", 50], ["tomato", 30]], t: ["herzhaft", "vegan"] },
  { n: "Vollkorn-Wrap mit Putenbrust", i: [["wrap", 64], ["turkeyham", 40], ["lettuce", 20], ["cheesecreamlt", 15]], t: ["herzhaft", "protein"] },
  { n: "Skyr mit Beeren & Honig", i: [["skyr", 150], ["berrymix", 60], ["honey", 10]], t: ["süß", "protein", "schnell"] },
  { n: "Magerquark mit Apfel", i: [["quark", 150], ["apple", 100]], t: ["süß", "protein"] },
  { n: "Quark mit Beeren & Leinsamen", i: [["quark", 150], ["berrymix", 60], ["flaxseed", 10]], t: ["süß", "protein"] },
  { n: "Griechischer Joghurt mit Walnüssen & Honig", i: [["yogurtgreek", 150], ["walnut", 15], ["honey", 8]], t: ["süß", "protein"] },
  { n: "Skyr mit Granola", i: [["skyr", 150], ["granola", 25]], t: ["süß", "protein", "schnell"] },
  { n: "Hüttenkäse mit Ananas", i: [["cottage", 120], ["pineapple", 80]], t: ["süß", "protein"] },
  { n: "Kiwi & Skyr", i: [["skyr", 150], ["kiwi", 75]], t: ["süß", "protein", "schnell"] },
  { n: "Banane mit Erdnussbutter", i: [["banana", 120], ["peanutbutter", 15]], t: ["süß", "schnell"] },
  { n: "Reiswaffeln mit Erdnussbutter & Banane", i: [["ricecake", 18], ["peanutbutter", 15], ["banana", 60]], t: ["süß", "schnell"] },
  { n: "Vollkorntoast mit Erdnussbutter & Banane", i: [["toast", 60], ["peanutbutter", 15], ["banana", 80]], t: ["süß"] },
  { n: "Reiswaffel mit Frischkäse & Gurke", i: [["ricecake", 18], ["cheesecreamlt", 25], ["cucumber", 40]], t: ["herzhaft", "schnell"] },
  { n: "Handvoll Mandeln & Apfel", i: [["almond", 25], ["apple", 150]], t: ["schnell", "vegan"] },
  { n: "Birne & Cashews", i: [["pear", 160], ["cashew", 20]], t: ["schnell", "vegan"] },
  { n: "Orange & Mandeln", i: [["orange", 180], ["almond", 20]], t: ["schnell", "vegan"] },
  { n: "Apfel & Zartbitterschokolade", i: [["apple", 150], ["chocdark", 15]], t: ["süß", "schnell"] },
  { n: "Weintrauben & Käsewürfel", i: [["grape", 100], ["cheese", 30]], t: ["schnell", "vegetarisch"] },
  { n: "Möhren-Sticks mit Hummus", i: [["carrot", 120], ["hummus", 40]], t: ["herzhaft", "vegan", "schnell"] },
  { n: "Gurken- & Paprikasticks mit Hüttenkäse", i: [["cucumber", 100], ["pepper", 80], ["cottage", 80]], t: ["herzhaft", "protein"] },
  { n: "Edamame-Snack", i: [["edamame", 120]], t: ["herzhaft", "vegan", "protein"] },
  { n: "Protein-Shake mit Banane", i: [["proteinpowder", 30], ["milk", 250], ["banana", 60]], t: ["süß", "protein", "schnell"] },
  { n: "Proteinriegel & Apfel", i: [["proteinbar", 60], ["apple", 150]], t: ["süß", "protein", "schnell"] },
  { n: "Vollkornbrot mit Harzer-Alternative & Senf", i: [["wgbread", 90], ["cottage", 60], ["mustard", 8]], t: ["herzhaft", "protein"] },
  { n: "Knäckebrot mit Thunfisch & Ei", i: [["crispbread", 20], ["tuna", 50], ["egg", 60]], t: ["herzhaft", "protein"] }
];
