/* APEX – Abendgerichte: proteinreich (>=46 g EW), 560–800 kcal, viel Comfort-Food.
   Format: { n:Name, i:[[zutatId, gramm], ...], t:[tags] } – kcal & EW berechnet die App.
   Reis/Nudeln/Couscous/Bulgur/Quinoa = Rohgewicht. ml-Zutaten (Öl, Sojasauce, Brühe, Kokosmilch) in ml. */

window.MEALS_DINNER = [
  { n: "Ofenlachs mit Süßkartoffel & Brokkoli", i: [["salmon", 200], ["sweetpotato", 150], ["broccoli", 180], ["oliveoil", 8], ["lemon", 20]], t: ["herzhaft", "protein", "warm"] },
  { n: "Teriyaki-Lachs mit Sushireis & Pak Choi", i: [["salmon", 200], ["sushirice", 55], ["pakchoi", 150], ["soysauce", 15], ["honey", 8], ["sesame", 6], ["ginger", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Lachs-Poke-Bowl mit Edamame", i: [["salmon", 160], ["sushirice", 60], ["edamame", 100], ["avocado", 40], ["cucumber", 80], ["soysauce", 12], ["sesame", 5], ["nori", 3]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Sushi-Bowl mit Thunfisch & Avocado", i: [["tuna", 150], ["sushirice", 60], ["edamame", 70], ["avocado", 40], ["cucumber", 80], ["soysauce", 12], ["sesame", 5], ["nori", 3]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Garnelen-Wok mit Mie-Nudeln", i: [["shrimp", 180], ["ricenoodle", 80], ["pakchoi", 100], ["pepper", 80], ["springonion", 20], ["soysauce", 15], ["sesameoil", 8], ["garlic", 6], ["chili", 4]], t: ["herzhaft", "protein", "warm", "schnell"] },
  { n: "Rote-Curry-Garnelen mit Basmatireis", i: [["shrimp", 190], ["rice", 55], ["coconutmilk", 70], ["currypaste", 20], ["pepper", 80], ["onion", 50], ["spinach", 60]], t: ["herzhaft", "protein", "warm"] },
  { n: "Kabeljau in Tomaten-Oliven-Sugo", i: [["cod", 220], ["passata", 150], ["olives", 30], ["parmesan", 20], ["potato", 180], ["onion", 60], ["garlic", 6], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Ofenkabeljau mit Parmesankruste & Kartoffeln", i: [["cod", 210], ["potato", 280], ["parmesan", 20], ["tomatocherry", 120], ["herbs", 8], ["oliveoil", 10]], t: ["herzhaft", "protein", "warm"] },
  { n: "Knuspriger Ofenlachs mit Quinoa & Feta", i: [["salmon", 180], ["quinoa", 45], ["rocket", 40], ["tomatocherry", 120], ["feta", 30], ["oliveoil", 6], ["lemon", 20]], t: ["herzhaft", "protein", "warm"] },
  { n: "Gebratene Forelle mit grünen Bohnen & Kartoffeln", i: [["trout", 200], ["greenbeans", 200], ["potato", 260], ["oliveoil", 8], ["lemon", 20], ["garlic", 5]], t: ["herzhaft", "protein", "warm"] },
  { n: "Mediterraner Thunfisch-Bohnen-Salat", i: [["tuna", 140], ["whitebeans", 140], ["tomato", 100], ["onionred", 40], ["rocket", 40], ["olives", 50], ["oliveoil", 18]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Lachs-Spinat-Pfanne mit Feta", i: [["salmon", 180], ["spinach", 200], ["feta", 40], ["garlic", 6], ["oliveoil", 8], ["lemon", 20]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Kabeljau-Curry mit Blumenkohlreis", i: [["cod", 240], ["cauliflower", 200], ["coconutmilk", 150], ["currypaste", 18], ["pepper", 80], ["onion", 50]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Garnelen-Zoodles mit Knoblauch & Parmesan", i: [["shrimp", 200], ["zucchini", 250], ["parmesan", 40], ["garlic", 8], ["tomatocherry", 120], ["oliveoil", 17]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Räucherlachs-Bowl mit Avocado & Ei", i: [["salmonsmoked", 120], ["egg", 120], ["avocado", 50], ["cucumber", 100], ["rocket", 40], ["sushirice", 50], ["soysauce", 10]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Ofenforelle mit Lauchgemüse & Kartoffeln", i: [["trout", 210], ["leek", 120], ["carrot", 100], ["potato", 180], ["lemon", 30], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Seelachs mit Ofengemüse & Feta", i: [["cod", 220], ["zucchini", 120], ["pepper", 100], ["eggplant", 100], ["feta", 70], ["oliveoil", 17]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Miso-Lachs-Ramen-Bowl", i: [["salmon", 160], ["udon", 140], ["pakchoi", 100], ["springonion", 20], ["soysauce", 15], ["ginger", 6], ["egg", 60], ["sesameoil", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Sesam-Thunfisch mit Wokgemüse", i: [["tuna", 190], ["broccoli", 150], ["carrot", 80], ["soysauce", 12], ["sesame", 15], ["sesameoil", 18], ["ginger", 6]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Garnelen-Feta-Pfanne mit Tomaten", i: [["shrimp", 190], ["tomatocherry", 150], ["feta", 70], ["spinach", 100], ["garlic", 8], ["oliveoil", 17]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Durchgebratenes Steak mit Süßkartoffel-Pommes", i: [["beefsteak", 190], ["sweetpotato", 200], ["broccoli", 120], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Steak-Bowl mit Reis & Avocado", i: [["beefsteak", 170], ["rice", 55], ["avocado", 40], ["tomatocherry", 100], ["rocket", 40], ["corn", 40]], t: ["herzhaft", "protein", "warm"] },
  { n: "Steaksalat mit Parmesan & Balsamico", i: [["beefsteak", 180], ["rocket", 60], ["tomatocherry", 120], ["parmesan", 35], ["cucumber", 80], ["oliveoil", 8], ["vinegar", 8]], t: ["herzhaft", "protein", "kalt", "lowcarb"] },
  { n: "Rinderhack-Bolognese auf Zucchininudeln", i: [["beefmince", 160], ["zucchini", 250], ["passata", 150], ["parmesan", 30], ["onion", 60], ["garlic", 6], ["oliveoil", 6]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Chili con Carne mit Kidneybohnen", i: [["beefmince", 160], ["beans", 150], ["passata", 150], ["corn", 50], ["pepper", 80], ["onion", 60], ["garlic", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Gefüllte Paprika mit Hack & Feta", i: [["beefmince", 170], ["pepper", 300], ["passata", 100], ["feta", 40], ["rice", 30], ["onion", 50]], t: ["herzhaft", "protein", "warm"] },
  { n: "Smash-Burger mit Cheddar & Salat", i: [["beefmince", 150], ["burgerbun", 80], ["cheese", 25], ["tomato", 40], ["lettuce", 30], ["onionred", 20], ["ketchup", 15], ["gherkin", 20]], t: ["herzhaft", "protein", "warm"] },
  { n: "Rind-Udon-Wok asiatisch", i: [["beefsteak", 160], ["udon", 150], ["pakchoi", 100], ["pepper", 70], ["soysauce", 15], ["sesameoil", 8], ["ginger", 6], ["garlic", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Steak mit Ofengemüse & Parmesan", i: [["beefsteak", 180], ["zucchini", 120], ["pepper", 120], ["onionred", 60], ["parmesan", 30], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Cheeseburger-Bowl ohne Brot", i: [["beefmince", 170], ["cheese", 40], ["avocado", 40], ["tomato", 60], ["lettuce", 40], ["gherkin", 20], ["onionred", 20], ["ketchup", 10], ["oliveoil", 5]], t: ["herzhaft", "protein", "lowcarb"] },
  { n: "Rinderhack-Pfanne mit Blumenkohlreis", i: [["beefmince", 160], ["cauliflower", 200], ["pepper", 80], ["onion", 60], ["passata", 80], ["parmesan", 25], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Steak-Fajita-Bowl", i: [["beefsteak", 170], ["pepper", 150], ["onionred", 80], ["tortilla", 65], ["tomato", 60], ["lettuce", 30]], t: ["herzhaft", "protein", "warm"] },
  { n: "Rinderhack-Zucchini-Auflauf mit Käse", i: [["beefmince", 160], ["zucchini", 200], ["passata", 120], ["cheese", 40], ["onion", 60], ["garlic", 6], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Steak-Sandwich mit Rucola & Parmesan", i: [["beefsteak", 160], ["roll", 70], ["rocket", 40], ["tomato", 60], ["parmesan", 20], ["oliveoil", 6]], t: ["herzhaft", "protein"] },
  { n: "Hähnchen-Parmesan in Tomatensauce", i: [["chicken", 170], ["passata", 150], ["parmesan", 30], ["cheesemozz", 40], ["herbs", 6], ["oliveoil", 6]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Hähnchen-Wok mit Mie-Nudeln", i: [["chicken", 150], ["ricenoodle", 70], ["broccoli", 120], ["carrot", 70], ["soysauce", 15], ["sesameoil", 8], ["ginger", 6], ["garlic", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchen-Ramen-Bowl mit Ei", i: [["chicken", 140], ["udon", 150], ["pakchoi", 100], ["egg", 60], ["springonion", 20], ["soysauce", 15], ["ginger", 6], ["sesameoil", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchen-Curry mit Basmatireis", i: [["chicken", 170], ["rice", 55], ["coconutmilk", 60], ["curry", 6], ["pepper", 80], ["onion", 50], ["spinach", 50]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchen-Bowl mit Quinoa & Avocado", i: [["chicken", 160], ["quinoa", 55], ["avocado", 40], ["tomatocherry", 100], ["rocket", 40], ["corn", 40]], t: ["herzhaft", "protein"] },
  { n: "Hähnchenspieße mit griechischem Salat", i: [["chicken", 170], ["cucumber", 120], ["tomato", 120], ["feta", 60], ["olives", 20], ["onionred", 40], ["oliveoil", 8]], t: ["herzhaft", "protein", "lowcarb"] },
  { n: "Putenbrust mit Ratatouille", i: [["turkey", 230], ["zucchini", 120], ["eggplant", 120], ["pepper", 100], ["passata", 100], ["oliveoil", 18]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Putengeschnetzeltes mit Champignons", i: [["turkey", 200], ["mushroom", 150], ["creamsour", 80], ["onion", 60], ["oliveoil", 13], ["herbs", 5]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Hähnchen-Fajita-Pfanne", i: [["chicken", 180], ["pepper", 150], ["onionred", 80], ["tortilla", 70], ["tomato", 60]], t: ["herzhaft", "protein", "warm"] },
  { n: "Buffalo-Chicken-Salat", i: [["chicken", 170], ["lettuce", 60], ["cucumber", 80], ["tomatocherry", 100], ["cheese", 40], ["cheesecreamlt", 40], ["chili", 4], ["oliveoil", 8]], t: ["herzhaft", "protein", "kalt", "lowcarb"] },
  { n: "Hähnchenschenkel mit Ofengemüse", i: [["chickenthigh", 240], ["carrot", 120], ["broccoli", 120], ["onion", 60], ["oliveoil", 6]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Puten-Zucchini-Feta-Pfanne", i: [["turkey", 180], ["zucchini", 200], ["tomatocherry", 100], ["feta", 70], ["oliveoil", 12]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Teriyaki-Hähnchen mit Reis & Sesam", i: [["chicken", 160], ["rice", 55], ["broccoli", 120], ["soysauce", 15], ["honey", 8], ["sesame", 8], ["ginger", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchen-Süßkartoffel-Bowl", i: [["chicken", 170], ["sweetpotato", 240], ["spinach", 60], ["avocado", 45], ["tomatocherry", 80]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchen Cordon bleu aus dem Ofen", i: [["chicken", 170], ["ham", 30], ["cheese", 50], ["broccoli", 150], ["oliveoil", 6]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Hähnchen-Kokos-Curry mit Blumenkohlreis", i: [["chicken", 170], ["cauliflower", 200], ["coconutmilk", 110], ["currypaste", 18], ["pepper", 80], ["onion", 50]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Putenspieße mit Ofengemüse & Hummus", i: [["turkey", 180], ["zucchini", 120], ["pepper", 120], ["hummus", 60], ["onionred", 50], ["oliveoil", 14]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchen-Caesar-Bowl", i: [["chicken", 170], ["lettuce", 80], ["parmesan", 40], ["tomatocherry", 80], ["cucumber", 80], ["yogurtgreek", 40], ["oliveoil", 6]], t: ["herzhaft", "protein", "kalt", "lowcarb"] },
  { n: "Hähnchen-Piccata mit Zucchini", i: [["chicken", 180], ["zucchini", 200], ["parmesan", 35], ["lemon", 30], ["egg", 30], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Pute süß-sauer mit Reis", i: [["turkey", 180], ["rice", 75], ["pepper", 100], ["pineapple", 60], ["carrot", 60], ["soysauce", 12]], t: ["herzhaft", "süß", "protein", "warm"] },
  { n: "Hähnchen-Gyros mit Tzatziki-Quark", i: [["chicken", 180], ["quark", 80], ["cucumber", 80], ["tomato", 80], ["onionred", 40], ["pita", 70]], t: ["herzhaft", "protein", "warm"] },
  { n: "Grüne-Curry-Hähnchen mit Reisnudeln", i: [["chicken", 160], ["ricenoodle", 60], ["coconutmilk", 60], ["currypaste", 18], ["pakchoi", 100], ["pepper", 70]], t: ["herzhaft", "protein", "warm"] },
  { n: "Tofu-Wok mit Mie-Nudeln", i: [["tofu", 200], ["ricenoodle", 60], ["edamame", 80], ["pakchoi", 100], ["soysauce", 15], ["sesameoil", 8], ["ginger", 6], ["garlic", 6]], t: ["herzhaft", "protein", "warm", "vegan"] },
  { n: "Räuchertofu-Curry mit Reis", i: [["tofusmoked", 220], ["rice", 55], ["coconutmilk", 60], ["currypaste", 18], ["pepper", 80], ["spinach", 60]], t: ["herzhaft", "protein", "warm", "vegan"] },
  { n: "Rote-Linsen-Dal mit Tofu", i: [["lentilsred", 90], ["tofu", 130], ["rice", 35], ["coconutmilk", 50], ["tomatopaste", 20], ["onion", 60], ["garlic", 6], ["ginger", 6]], t: ["herzhaft", "protein", "warm", "vegan"] },
  { n: "Linsen-Bolognese auf Vollkornnudeln", i: [["lentilsred", 130], ["pasta", 35], ["passata", 150], ["parmesan", 20], ["onion", 60], ["garlic", 6], ["carrot", 60]], t: ["herzhaft", "protein", "warm"] },
  { n: "Chili sin Carne mit Tofu", i: [["tofu", 150], ["beans", 150], ["lentilsred", 40], ["passata", 150], ["corn", 50], ["pepper", 80], ["onion", 60]], t: ["herzhaft", "protein", "warm", "vegan"] },
  { n: "Halloumi-Salat mit Oliven & Hummus", i: [["halloumi", 150], ["chickpeas", 170], ["hummus", 20], ["cucumber", 100], ["tomato", 100], ["rocket", 30], ["olives", 15], ["lemon", 20]], t: ["herzhaft", "protein", "warm", "vegetarisch"] },
  { n: "Gebratener Halloumi mit Ofengemüse & Ei", i: [["halloumi", 150], ["egg", 120], ["zucchini", 120], ["pepper", 120], ["eggplant", 100], ["oliveoil", 5]], t: ["herzhaft", "protein", "warm", "vegetarisch"] },
  { n: "Kichererbsen-Feta-Pfanne mit Ei", i: [["chickpeas", 200], ["egg", 180], ["feta", 60], ["zucchini", 120], ["tomatocherry", 120], ["onion", 50], ["oliveoil", 6]], t: ["herzhaft", "protein", "warm", "vegetarisch"] },
  { n: "Shakshuka mit Feta & Kichererbsen", i: [["egg", 180], ["chickpeas", 180], ["passata", 200], ["feta", 50], ["pepper", 100], ["onion", 60], ["garlic", 6]], t: ["herzhaft", "protein", "warm", "vegetarisch"] },
  { n: "Protein-Omelett mit Käse & Spinat", i: [["egg", 180], ["eggwhite", 120], ["cheese", 50], ["spinach", 100], ["tomato", 60], ["oliveoil", 6]], t: ["herzhaft", "protein", "vegetarisch", "lowcarb"] },
  { n: "Gefüllte Paprika mit Quinoa & Feta-Quark", i: [["pepper", 300], ["quark", 180], ["chickpeas", 140], ["quinoa", 40], ["feta", 50], ["passata", 60], ["onion", 50]], t: ["herzhaft", "protein", "warm", "vegetarisch"] },
  { n: "Tofu-Teriyaki mit Reis & Brokkoli", i: [["tofusmoked", 210], ["rice", 55], ["broccoli", 120], ["soysauce", 15], ["maple", 8], ["sesame", 8], ["ginger", 6]], t: ["herzhaft", "protein", "warm", "vegan"] },
  { n: "Kichererbsen-Tofu-Curry", i: [["tofu", 200], ["chickpeas", 150], ["rice", 35], ["coconutmilk", 60], ["spinach", 60], ["curry", 6], ["tomatopaste", 20], ["onion", 60]], t: ["herzhaft", "protein", "warm", "vegan"] },
  { n: "Edamame-Poke-Bowl mit Tofu", i: [["tofu", 190], ["edamame", 100], ["sushirice", 60], ["cucumber", 80], ["avocado", 40], ["soysauce", 12], ["sesame", 5]], t: ["herzhaft", "protein", "kalt", "vegan"] },
  { n: "Linsen-Feta-Salat mit Ei", i: [["lentils", 220], ["feta", 70], ["egg", 120], ["tomato", 100], ["cucumber", 80], ["onionred", 40], ["rocket", 40], ["oliveoil", 8]], t: ["herzhaft", "protein", "kalt", "vegetarisch"] },
  { n: "Hüttenkäse-Bowl mit Ei & Gemüse", i: [["cottage", 230], ["egg", 120], ["cucumber", 100], ["tomatocherry", 100], ["rocket", 30], ["wgbread", 65]], t: ["herzhaft", "protein", "kalt", "vegetarisch"] },
  { n: "Ofen-Feta-Pasta mit Hähnchen", i: [["chicken", 140], ["feta", 70], ["pasta", 55], ["tomatocherry", 200], ["garlic", 6], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Tofu-Ramen-Bowl", i: [["tofusmoked", 180], ["udon", 150], ["pakchoi", 100], ["edamame", 60], ["soysauce", 15], ["ginger", 6], ["sesameoil", 6]], t: ["herzhaft", "protein", "warm", "vegan"] },
  { n: "Quark-Kräuter-Bowl mit Ei & Kartoffeln", i: [["quark", 250], ["egg", 120], ["potato", 220], ["cucumber", 100], ["tomato", 80], ["herbs", 8], ["oliveoil", 5]], t: ["herzhaft", "protein", "kalt", "vegetarisch"] },
  { n: "Frittata mit Gemüse & Käse", i: [["egg", 200], ["eggwhite", 120], ["cheese", 40], ["zucchini", 120], ["pepper", 100], ["onion", 50], ["oliveoil", 6]], t: ["herzhaft", "protein", "vegetarisch", "lowcarb"] },
  { n: "Vegane Buddha-Bowl mit Räuchertofu", i: [["tofusmoked", 180], ["quinoa", 45], ["edamame", 70], ["avocado", 40], ["carrot", 80], ["rocket", 40], ["hummus", 30]], t: ["herzhaft", "protein", "kalt", "vegan"] },
  { n: "Linsen-Kokos-Curry mit Tofu & Spinat", i: [["lentilsred", 90], ["tofu", 150], ["coconutmilk", 40], ["spinach", 120], ["tomatopaste", 20], ["onion", 60], ["garlic", 6], ["rice", 30]], t: ["herzhaft", "protein", "warm", "vegan"] },
  { n: "Mozzarella-Tomaten-Bowl mit Ei", i: [["cheesemozz", 130], ["egg", 120], ["tomato", 150], ["rocket", 40], ["wgbread", 45], ["pesto", 15]], t: ["herzhaft", "protein", "vegetarisch"] },
  { n: "Tofu-Steak mit Erdnusssauce & Brokkoli", i: [["tofu", 200], ["broccoli", 150], ["peanutbutter", 25], ["soysauce", 12], ["ricenoodle", 40], ["ginger", 6]], t: ["herzhaft", "protein", "warm", "vegan"] },
  { n: "Hähnchen-Cheeseburger-Bowl", i: [["chicken", 170], ["cheese", 25], ["burgerbun", 70], ["tomato", 40], ["lettuce", 30], ["onionred", 20], ["ketchup", 12]], t: ["herzhaft", "protein", "warm"] },
  { n: "Putenschnitzel mit Kartoffelsalat", i: [["turkey", 210], ["potato", 280], ["cucumber", 80], ["yogurtgreek", 40], ["onion", 40], ["mustard", 6]], t: ["herzhaft", "protein"] },
  { n: "Räucherlachs-Frischkäse-Wrap", i: [["salmonsmoked", 120], ["cheesecreamlt", 60], ["wrap", 64], ["cucumber", 60], ["rocket", 30], ["lettuce", 30], ["egg", 60]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Thunfisch-Melt auf Vollkornbrot", i: [["tuna", 150], ["cheese", 40], ["wgbread", 110], ["tomato", 60], ["onionred", 20], ["corn", 30]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchen-Pesto-Pasta", i: [["chicken", 140], ["pasta", 55], ["pesto", 20], ["tomatocherry", 120], ["parmesan", 20], ["rocket", 30]], t: ["herzhaft", "protein", "warm"] },
  { n: "Garnelen-Aglio-Olio mit Vollkornnudeln", i: [["shrimp", 180], ["pasta", 65], ["garlic", 10], ["chili", 4], ["rocket", 30], ["parmesan", 20], ["oliveoil", 10]], t: ["herzhaft", "protein", "warm"] },
  { n: "Steak-Quesadilla mit Käse", i: [["beefsteak", 150], ["tortilla", 60], ["cheese", 40], ["pepper", 80], ["onionred", 40], ["tomato", 40]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchen-Enchilada-Bowl", i: [["chicken", 140], ["beans", 80], ["passata", 120], ["cheese", 30], ["corn", 40], ["pepper", 80], ["rice", 30]], t: ["herzhaft", "protein", "warm"] },
  { n: "Poke-Bowl mit Lachs & Mango", i: [["salmon", 170], ["sushirice", 60], ["mango", 50], ["edamame", 70], ["cucumber", 80], ["avocado", 30], ["soysauce", 12]], t: ["herzhaft", "süß", "protein", "kalt"] },
  { n: "Hähnchen-Halloumi-Spieße mit Couscous", i: [["chicken", 120], ["halloumi", 80], ["couscous", 40], ["zucchini", 120], ["pepper", 120], ["oliveoil", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchen-Döner-Bowl mit Joghurtsauce", i: [["chicken", 190], ["cabbage", 80], ["tomato", 80], ["cucumber", 80], ["yogurtgreek", 50], ["onionred", 40], ["pita", 55]], t: ["herzhaft", "protein", "warm"] },
  { n: "Rindfleisch-Pho-Bowl", i: [["beefsteak", 160], ["udon", 150], ["beansprouts", 60], ["pakchoi", 80], ["springonion", 20], ["soysauce", 12], ["ginger", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Lachs-Nudel-Wok in Sojasauce", i: [["salmon", 180], ["ricenoodle", 60], ["broccoli", 120], ["carrot", 60], ["soysauce", 15], ["sesameoil", 8], ["ginger", 6]], t: ["herzhaft", "protein", "warm"] },
  { n: "Hähnchen-Brokkoli-Auflauf mit Käse", i: [["chicken", 140], ["broccoli", 200], ["cheese", 40], ["creamsour", 50], ["onion", 50], ["oliveoil", 6]], t: ["herzhaft", "protein", "warm", "lowcarb"] },
  { n: "Feurige Garnelen-Tacos", i: [["shrimp", 210], ["tortilla", 70], ["avocado", 90], ["lettuce", 40], ["tomato", 60], ["lime", 20], ["chili", 4]], t: ["herzhaft", "protein", "warm"] },
  { n: "Putencurry mit Süßkartoffel", i: [["turkey", 180], ["sweetpotato", 210], ["coconutmilk", 60], ["curry", 6], ["spinach", 60], ["onion", 50]], t: ["herzhaft", "protein", "warm"] },
  { n: "Sushi-Bowl mit Lachs & Gurke", i: [["salmon", 160], ["sushirice", 60], ["cucumber", 100], ["avocado", 40], ["edamame", 70], ["soysauce", 12], ["nori", 3], ["sesame", 5]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Hähnchen-Saltimbocca mit Schinken", i: [["chicken", 150], ["ham", 30], ["parmesan", 15], ["spinach", 150], ["potato", 180], ["oliveoil", 8]], t: ["herzhaft", "protein", "warm"] },
  { n: "Linsen-Hackpfanne mit Feta", i: [["beefmince", 140], ["lentils", 150], ["passata", 120], ["feta", 40], ["onion", 60], ["spinach", 60]], t: ["herzhaft", "protein", "warm"] },
  { n: "Halloumi-Burger mit Spiegelei", i: [["halloumi", 130], ["egg", 120], ["burgerbun", 60], ["tomato", 40], ["lettuce", 30], ["onionred", 20]], t: ["herzhaft", "protein", "warm", "vegetarisch"] },
];
