/* APEX – Brotzeit für vormittags (~10 Uhr, Schulpause: transportabel, gut vorzubereiten)
   Fokus: gesund & sehr proteinreich (>=24 g Eiweiß), herzhaft bevorzugt, kein Zucker-/Junk-Snack.
   Format: { n:Name, i:[[zutatId, gramm], ...], t:[tags] }  – kcal/Eiweiß berechnet die App. */

window.MEALS_SNACK = [
  { n: "Vollkornbrot mit Käse, Schinken & Gurke", i: [["wgbread", 90], ["cheese", 40], ["ham", 50], ["cucumber", 40], ["mustard", 5]], t: ["herzhaft", "protein"] },
  { n: "Roggenbrot mit Hüttenkäse, Pute & Tomate", i: [["ryebread", 80], ["cottage", 100], ["turkeyham", 50], ["tomato", 40]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Vollkornbrot mit Thunfisch-Frischkäse-Creme", i: [["wgbread", 90], ["tuna", 70], ["cheesecreamlt", 25], ["cucumber", 30]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Vollkornbrötchen mit Räucherlachs, Ei & Frischkäse", i: [["roll", 70], ["salmonsmoked", 50], ["cheesecreamlt", 30], ["egg", 60]], t: ["herzhaft", "protein"] },
  { n: "Vollkornbrot mit Rührei & Käse", i: [["wgbread", 45], ["egg", 120], ["cheese", 25], ["tomato", 40]], t: ["herzhaft", "protein"] },
  { n: "Vollkorn-Wrap mit Pute & Frischkäse", i: [["wrap", 64], ["turkeyham", 80], ["cheesecreamlt", 30], ["lettuce", 20]], t: ["herzhaft", "protein", "schnell"] },
  { n: "Vollkorn-Pita mit Hähnchen & Joghurt-Dip", i: [["pita", 70], ["chicken", 80], ["yogurtgreek", 30], ["lettuce", 20], ["cucumber", 30]], t: ["herzhaft", "protein"] },
  { n: "Knäckebrot mit Hüttenkäse, Tomate & Kürbiskernen", i: [["crispbread", 20], ["cottage", 150], ["tomatocherry", 50], ["pumpkinseed", 15]], t: ["herzhaft", "protein", "vegetarisch"] },
  { n: "Knäckebrot mit Thunfisch & Ei", i: [["crispbread", 30], ["tuna", 80], ["egg", 60], ["tomato", 30]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Vollkornbrot mit körnigem Frischkäse & Senf", i: [["wgbread", 90], ["cottage", 150], ["mustard", 8], ["radish", 30]], t: ["herzhaft", "protein", "vegetarisch"] },
  { n: "Mozzarella-Tomaten-Snackbox mit Basilikum", i: [["cheesemozz", 120], ["tomatocherry", 100], ["oliveoil", 5], ["herbs", 3]], t: ["herzhaft", "protein", "vegetarisch", "kalt"] },
  { n: "Feta-Hüttenkäse-Box mit Oliven & Tomate", i: [["feta", 70], ["cottage", 120], ["olives", 20], ["tomatocherry", 70], ["cucumber", 40]], t: ["herzhaft", "protein", "vegetarisch", "kalt"] },
  { n: "Edamame mit Meersalz & Ei", i: [["edamame", 170], ["egg", 60]], t: ["herzhaft", "protein", "vegetarisch"] },
  { n: "Edamame-Schote mit Chili & Meersalz", i: [["edamame", 230], ["chili", 3]], t: ["herzhaft", "protein", "vegan"] },
  { n: "Protein-Shake mit Banane & Beeren", i: [["proteinpowder", 30], ["milk", 250], ["banana", 60]], t: ["süß", "protein", "schnell"] },
  { n: "Protein-Shake mit Erdnussbutter & Banane", i: [["proteinpowder", 30], ["milk", 200], ["peanutbutter", 10], ["banana", 60]], t: ["süß", "protein", "schnell"] },
  { n: "Skyr-Protein-Bowl mit Beeren & Mandeln", i: [["skyr", 250], ["berrymix", 60], ["almond", 15]], t: ["süß", "protein", "kalt"] },
  { n: "Magerquark mit Beeren, Leinsamen & Honig", i: [["quark", 250], ["berrymix", 80], ["flaxseed", 12], ["honey", 8]], t: ["süß", "protein"] },
  { n: "Magerquark mit Banane & Haferflocken", i: [["quark", 200], ["banana", 80], ["oats", 25]], t: ["süß", "protein"] },
  { n: "Skyr mit Apfel & Walnüssen", i: [["skyr", 250], ["apple", 100], ["walnut", 12]], t: ["süß", "protein"] },
  { n: "Hüttenkäse-Bowl mit Ananas & Kürbiskernen", i: [["cottage", 200], ["pineapple", 80], ["pumpkinseed", 12]], t: ["süß", "protein"] },
  { n: "Griechischer Joghurt-Bowl mit Beeren & Protein", i: [["yogurtgreek", 150], ["proteinpowder", 20], ["berrymix", 50]], t: ["süß", "protein"] },
  { n: "Hüttenkäse-Bowl mit Gurke, Tomate & Kürbiskern", i: [["cottage", 220], ["cucumber", 60], ["tomatocherry", 60], ["pumpkinseed", 10]], t: ["herzhaft", "protein", "lowcarb", "kalt"] },
  { n: "Gemüsesticks mit Skyr-Dip & Knäcke", i: [["carrot", 100], ["cucumber", 80], ["skyr", 220], ["crispbread", 30]], t: ["herzhaft", "protein", "schnell"] },
  { n: "Hummus-Wrap mit Räuchertofu & Paprika", i: [["wrap", 64], ["hummus", 25], ["tofusmoked", 90], ["pepper", 50], ["lettuce", 20]], t: ["herzhaft", "protein", "vegan"] },
  { n: "Käse-Schinken-Röllchen", i: [["cheese", 50], ["ham", 60], ["turkeyham", 30], ["cucumber", 60]], t: ["herzhaft", "protein", "lowcarb"] },
  { n: "Putenbrust-Frischkäse-Röllchen mit Paprika", i: [["turkeyham", 100], ["cheesecreamlt", 50], ["cheese", 30], ["pepper", 80]], t: ["herzhaft", "protein", "lowcarb"] },
  { n: "Räucherlachs-Frischkäse-Röllchen mit Gurke", i: [["salmonsmoked", 80], ["cheesecreamlt", 60], ["cucumber", 80], ["cottage", 40]], t: ["herzhaft", "protein", "lowcarb", "kalt"] },
  { n: "Thunfisch-Bohnen-Box mit Ei", i: [["tuna", 70], ["egg", 60], ["beans", 60], ["corn", 40], ["lettuce", 30], ["tomatocherry", 40]], t: ["herzhaft", "protein", "kalt"] },
  { n: "Kichererbsen-Edamame-Salat mit Feta", i: [["chickpeas", 120], ["feta", 50], ["edamame", 80], ["tomatocherry", 60], ["cucumber", 40]], t: ["herzhaft", "protein", "vegetarisch", "kalt"] },
  { n: "Linsensalat mit Feta & Tomate", i: [["lentils", 180], ["feta", 70], ["tomatocherry", 60], ["cucumber", 40]], t: ["herzhaft", "protein", "vegetarisch", "kalt"] },
  { n: "Mozzarella-Schinken-Spieße mit Tomate", i: [["cheesemozz", 100], ["ham", 40], ["tomatocherry", 100], ["oliveoil", 3]], t: ["herzhaft", "protein", "lowcarb", "kalt"] },
  { n: "Hüttenkäse mit Beeren, Protein & Haferflocken", i: [["cottage", 150], ["berrymix", 60], ["proteinpowder", 10], ["oats", 20]], t: ["süß", "protein"] },
  { n: "Skyr-Bowl mit Banane, Erdnussbutter & Kakao", i: [["skyr", 200], ["banana", 80], ["peanutbutter", 12], ["cocoa", 5]], t: ["süß", "protein"] },
  { n: "Vollkornbrötchen mit Ei-Aufstrich", i: [["roll", 70], ["egg", 120], ["cheesecreamlt", 20], ["cottage", 30], ["springonion", 10]], t: ["herzhaft", "protein"] },
  { n: "Vollkornbrot mit Hähnchen & Senf", i: [["wgbread", 90], ["chicken", 80], ["lettuce", 20], ["mustard", 5], ["tomato", 30]], t: ["herzhaft", "protein"] }
];
